language: python
python: 
 - "3.4"
 - "3.5"
 - "3.6"

#install dependencies
install:
 - cd pydash
 - mkdir -p logs
 - pip install pipenv
 - export FLASK_APP=pydash.py
 - export FLASK_ENV=development
 - pipenv install --dev

#run pytest
script:
 - pipenv run pytest
