language: python
python:
 - "3.6"

#install dependencies
install:
 - wget https://github.com/mozilla/geckodriver/releases/download/v0.11.1/geckodriver-v0.11.1-linux64.tar.gz
 - mkdir geckodriver
 - tar -xzf geckodriver-v0.11.1-linux64.tar.gz -C geckodriver
 - export PATH=$PATH:$PWD/geckodriver
 - cd pydash
 - mkdir -p logs
 - pip install pipenv
 - export FLASK_APP=pydash.py
 - export FLASK_ENV=development
 - pipenv install --dev

#run pytest
script:
 - pipenv run pytest
