# language and version specifications
language: python
rvm: 
 - "3.4"
 - "3.5"
 - "3.6"

#install dependencies
install:
 - cd pydash
 - ./start_pipenv.sh
 - pipenv install --dev

#run pytest
script:
 - pytest
